Update .gitlab-ci.yml file

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -77,27 +77,13 @@ release:
     - job: publish
       artifacts: true
 
-  before_script: []
-
   script:
     - |
-      echo "Checking if release exists..."
-
-      STATUS=$(curl -s -o /dev/null -w "%{http_code}" \
-        --header "JOB-TOKEN: $CI_JOB_TOKEN" \
-        "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/v$VERSION")
-
-      if [ "$STATUS" = "200" ]; then
-        echo "Release already exists. Skipping."
-        exit 0
-      fi
-
-      echo "Creating release..."
       release-cli create \
         --tag-name "v$VERSION" \
         --name "Huragok v$VERSION" \
         --description "Automated release for v$VERSION" \
-        --assets-link "{\"name\":\"Huragok version $VERSION, for Halo Reach\",\"url\":\"$PACKAGE_URL\"}"
+        --assets-link "{\"name\":\"Huragok version $VERSION, for Halo Reach\",\"url\":\"$PACKAGE_URL\"}" || echo "Release already exists or submission failed."
 
   rules:
     - if: '$CI_COMMIT_BRANCH == "main"'
